version: "1.7"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      BOT_NAME: $BOT_NAME
      SUDO_USERS: $SUDO_USERS
      SESSION_NAME: $SESSION_NAME
      DURATION_LIMIT: $DURATION_LIMIT
      SUPPORT_GROUP: $SUPPORT_GROUP
      ARQ_API_KEY: $ARQ_API_KEY
      ARQ_API_URL: $ARQ_API_URL
      BOT_USERNAME: $BOT_USERNAME
      OWNER_NAME: $OWNER_NAME
      START_IMG: $START_IMG
      PING_IMG: $PING_IMG
      COMMAND_PREFIXES: $COMMAND_PREFIXES
      PM_PERMIT: $PM_PERMIT
      MONGODB_URL:$MONGODB_URL
      DEV_NAME:$DEV_NAME
      DEV_PHOTO:$DEV_PHOTO
      BOT_PHOTO:$BOT_PHOTO
      ALIVE_NAME:$ALIVE_NAME
      UPSTREAM_BRANCH:$UPSTREAM_BRANCH
      UPSTREAM_REPO:$UPSTREAM_REPO
      UPDATES_CHANNEL:$UPDATES_CHANNEL
      ASSISTANT_NAME:$ASSISTANT_NAME
